### ISSUE TITLE
Query can throw AttributeError: 'NoneType' object has no attribute 'find_all'

### ISSUE THREAD

**Issue by dominicprice** [2e0byo/durham-directory#1]
A slightly misleading `AttributeError` is thrown when a name not in the directory is searched, e.g.

```
>>> from durham_directory import Query
>>> query = Query(my_username)
Password:
>>> query(oname="bill", surname="gates")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\domin\AppData\Roaming\Python\Python39\site-packages\durham_directory\__init__.py", line 30, in __call__
    keys, *rows = results.find_all("tr")
AttributeError: 'NoneType' object has no attribute 'find_all'
```

Probably a separate issue, but this error is also sometimes raised for an `oname` which *is* in the directory:

```
>>> query(oname="Matthew")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\domin\AppData\Roaming\Python\Python39\site-packages\durham_directory\__init__.py", line 30, in __call__
    keys, *rows = results.find_all("tr")
AttributeError: 'NoneType' object has no attribute 'find_all'
```

although the same query passing in a valid surname correctly returns a result. 

Python version is 3.9.7.

**Comment by 2e0byo** [comment]
Fixed in a9db5d7; ta.  Annoying they don't give the no matches the class 'error'.  New version pushed to pypi.
